<?php

declare(strict_types=1);

namespace App\Filament\Resources;

use App\Filament\Resources\SaleResource\Pages\ManageSales;
use App\Models\Category;
use App\Models\Sale;
use Filament\Forms;
use Filament\Resources\Resource;
use Filament\Schemas\Schema;
use Filament\Tables;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;

class SaleResource extends Resource
{
    protected static ?string $model = Sale::class;

    protected static string|\BackedEnum|null $navigationIcon = 'heroicon-o-receipt-percent';

    protected static string|\UnitEnum|null $navigationGroup = 'Operations';

    public static function form(Schema $schema): Schema
    {
        return $schema->schema([
            Forms\Components\Placeholder::make('read_only')
                ->content('Sales are generated by checkout and remain read-only in the command center.'),
        ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->defaultSort('created_at', 'desc')
            ->modifyQueryUsing(fn (Builder $query) => $query->with(['user', 'payments', 'saleItems.product.category']))
            ->columns([
                Tables\Columns\TextColumn::make('created_at')
                    ->dateTime('d M H:i')
                    ->sortable(),
                Tables\Columns\TextColumn::make('receipt_number')
                    ->searchable()
                    ->copyable()
                    ->label('Transaction'),
                Tables\Columns\TextColumn::make('user.name')
                    ->label('Cashier')
                    ->searchable(),
                Tables\Columns\TextColumn::make('payments_summary')
                    ->label('Payment')
                    ->getStateUsing(fn (Sale $record): string => $record->payments->pluck('method')->unique()->map(fn (string $method): string => strtoupper($method))->join(', '))
                    ->badge(),
                Tables\Columns\TextColumn::make('grand_total')
                    ->formatStateUsing(fn ($state): string => 'KES ' . number_format((float) $state, 2))
                    ->alignEnd()
                    ->sortable(),
                Tables\Columns\TextColumn::make('status')
                    ->badge(),
            ])
            ->filters([
                Tables\Filters\Filter::make('date_range')
                    ->form([
                        Forms\Components\DatePicker::make('from'),
                        Forms\Components\DatePicker::make('until'),
                    ])
                    ->query(function (Builder $query, array $data): Builder {
                        return $query
                            ->when($data['from'] ?? null, fn (Builder $builder, $date) => $builder->whereDate('created_at', '>=', $date))
                            ->when($data['until'] ?? null, fn (Builder $builder, $date) => $builder->whereDate('created_at', '<=', $date));
                    }),
                Tables\Filters\SelectFilter::make('category')
                    ->options(fn (): array => Category::query()->orderBy('name')->pluck('name', 'id')->all())
                    ->query(function (Builder $query, array $data): Builder {
                        return $query->when($data['value'] ?? null, fn (Builder $builder, $value) => $builder->whereHas('saleItems.product', fn (Builder $productQuery) => $productQuery->where('category_id', $value)));
                    }),
                Tables\Filters\SelectFilter::make('payment_method')
                    ->options([
                        'cash' => 'Cash',
                        'mpesa' => 'M-PESA',
                        'card' => 'Card',
                        'credit_deni' => 'Credit Deni',
                    ])
                    ->query(fn (Builder $query, array $data) => $query->when($data['value'] ?? null, fn (Builder $builder, $value) => $builder->whereHas('payments', fn (Builder $paymentQuery) => $paymentQuery->where('method', $value)))),
            ])
            ->paginated([50, 100, 250])
            ->defaultPaginationPageOption(100);
    }

    public static function canCreate(): bool
    {
        return false;
    }

    public static function canEdit($record): bool
    {
        return false;
    }

    public static function canDelete($record): bool
    {
        return false;
    }

    public static function getPages(): array
    {
        return [
            'index' => ManageSales::route('/'),
        ];
    }
}
